server:
  port: 8082

info:
  app:
    name: inventario-service
    description: Microservicio de gestión de inventario
    version: 1.0.0

spring:
  datasource:
    url: jdbc:mysql://pruebas-1.cnuomwmmsvob.us-east-2.rds.amazonaws.com:3306/prueba_tecnica_dev
    username: admin
    password: admin2025*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  api-key: secreta123
  product-service-url: http://producto-service:8081
